version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: exampleUser
      MONGO_INITDB_ROOT_PASSWORD: examplePassword
      MONGO_INITDB_DATABASE: ecosite
    ports:
      - "27017:27017"

  nestjs_app:
    build: ./backend/.
    container_name: nestjs_app
    depends_on:
      - mongodb
    networks:
      - mongodb_network
    environment:
      DATABASE_URL: mongodb://mongodb:27017/ecosite
    ports:
      - "3000:3000"
  vue_app:
    build: ./frontend/.
    container_name: vue_app
    depends_on:
      - nestjs_app
    ports:
      - "8080:8080"
    networks:
      - mongodb_network

volumes:
  mongodb_data:

networks:
  mongodb_network:
    driver: bridge
